#!/usr/bin/env bash
#
# --- USAGE-START ---  (sentinel for usage(); do not remove)
# create-team-projects.sh -- Generate one Claude Code project per Agency team.
#
# For every division (team) in the repo this creates <dest>/<team>/ containing:
#   .claude/agents/   project-scoped copies of that team's agents
#   CLAUDE.md         team charter: what the team does + the full roster
#
# Open any generated folder in Claude Code (desktop app or CLI) and that
# team's agents load as project subagents -- no global install required.
#
# Usage:
#   ./scripts/create-team-projects.sh [options]
#
# Options:
#   --dest <dir>       Where to create the projects (default: ~/AgencyTeams)
#   --division <a,b>   Only these teams (comma-separated; default: all)
#   --link             Symlink agent files instead of copying (updates propagate)
#   --force            Overwrite an existing CLAUDE.md (agents are always refreshed)
#   --dry-run          Print the plan and exit without writing anything
#   --help             Show this help
# --- USAGE-END ---
#
# Platform support: Linux, macOS (bash 3.2+), Windows Git Bash / WSL

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Shared helpers (get_field, agent_slug, is_agent_file, slugify, incr)
# shellcheck source=lib.sh
. "$SCRIPT_DIR/lib.sh"

if supports_color; then
  C_GREEN=$'\033[0;32m'; C_YELLOW=$'\033[1;33m'; C_RED=$'\033[0;31m'
  C_BOLD=$'\033[1m'; C_DIM=$'\033[2m'; C_RESET=$'\033[0m'
else
  C_GREEN=''; C_YELLOW=''; C_RED=''; C_BOLD=''; C_DIM=''; C_RESET=''
fi
ok()     { printf "${C_GREEN}[OK]${C_RESET}  %s\n" "$*"; }
warn()   { printf "${C_YELLOW}[!!]${C_RESET}  %s\n" "$*"; }
err()    { printf "${C_RED}[ERR]${C_RESET} %s\n" "$*" >&2; }
header() { printf "\n${C_BOLD}%s${C_RESET}\n" "$*"; }
dim()    { printf "${C_DIM}%s${C_RESET}\n" "$*"; }

# Keep in sync with ALL_DIVISIONS in install.sh (divisions.json is the source
# of truth; strategy/ is excluded -- playbooks, not frontmatter agents).
ALL_DIVISIONS=(
  academic design engineering finance game-development gis marketing paid-media
  product project-management sales security spatial-computing specialized support testing
)

usage() {
  sed -n '/^# --- USAGE-START ---/,/^# --- USAGE-END ---/p' "$0" \
    | sed -e '1d;$d' -e 's/^# \{0,1\}//'
  exit 0
}

validate_division() {
  local d
  for d in "${ALL_DIVISIONS[@]}"; do [[ "$d" == "$1" ]] && return 0; done
  err "Unknown division '$1'. Valid: ${ALL_DIVISIONS[*]}"
  exit 1
}

# division_label <division> -- display label from divisions.json, slug fallback.
division_label() {
  local l
  l="$(sed -n 's/.*"'"$1"'": { "label": "\([^"]*\)".*/\1/p' "$REPO_ROOT/divisions.json" | head -1)"
  if [[ -n "$l" ]]; then printf '%s' "$l"; else printf '%s' "$1"; fi
}

# division_files <division> -- frontmatter agent files in a division.
division_files() {
  local d="$REPO_ROOT/$1" f
  [[ -d "$d" ]] || return 0
  while IFS= read -r -d '' f; do
    is_agent_file "$f" && printf '%s\n' "$f"
  done < <(find "$d" -name "*.md" -type f -print0 2>/dev/null | sort -z)
}

# short_desc <file> -- frontmatter description trimmed to one readable line.
short_desc() {
  local desc
  desc="$(get_field description "$1")"
  desc="${desc%%<example>*}"                 # drop inline usage examples
  desc="$(printf '%s' "$desc" | tr -s ' ' | sed 's/^ //; s/ $//')"
  if [[ ${#desc} -gt 180 ]]; then desc="${desc:0:177}..."; fi
  printf '%s' "$desc"
}

install_file() {
  if $USE_LINK; then ln -sf "$1" "$2"; else cp "$1" "$2"; fi
}

write_claude_md() {
  local division="$1" label="$2" dest="$3" f name desc
  {
    printf '# The Agency — %s Team\n\n' "$label"
    printf 'This is a Claude Code project for The Agency'"'"'s **%s** team.\n' "$label"
    printf 'The team'"'"'s specialist agents are installed project-locally in `.claude/agents/`,\n'
    printf 'so opening this folder in Claude Code loads exactly this roster.\n\n'
    printf '## Working with the team\n\n'
    printf -- '- Describe your task and Claude Code will auto-delegate to a matching specialist.\n'
    printf -- '- Or address one directly: "Use the <agent-name> agent to ...".\n'
    printf -- '- Run `/agents` to browse this team'"'"'s roster inside a session.\n\n'
    printf '## Roster\n\n'
    while IFS= read -r f; do
      name="$(get_field name "$f")"
      desc="$(short_desc "$f")"
      if [[ -n "$desc" ]]; then
        printf -- '- **%s** — %s\n' "$name" "$desc"
      else
        printf -- '- **%s**\n' "$name"
      fi
    done < <(division_files "$division")
    printf '\n---\n\nGenerated by `scripts/create-team-projects.sh` in the agency-agents repo.\n'
    printf 'Re-run it after updating agents to refresh this project.\n'
  } > "$dest/CLAUDE.md"
}

# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
DEST="${HOME}/AgencyTeams"
USE_LINK=false
FORCE=false
DRY_RUN=false
SELECTED=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dest)     DEST="${2:?'--dest requires a value'}"; shift 2 ;;
    --division)
      IFS=',' read -ra _divs <<< "${2:?'--division requires a value'}"
      for _d in "${_divs[@]}"; do
        _d="$(printf '%s' "$_d" | xargs)"; [[ -z "$_d" ]] && continue
        validate_division "$_d"; SELECTED+=("$_d")
      done
      shift 2 ;;
    --link)     USE_LINK=true; shift ;;
    --force)    FORCE=true; shift ;;
    --dry-run)  DRY_RUN=true; shift ;;
    --help|-h)  usage ;;
    *)          err "Unknown option: $1"; usage ;;
  esac
done

[[ ${#SELECTED[@]} -eq 0 ]] && SELECTED=("${ALL_DIVISIONS[@]}")

header "The Agency -- Creating team projects"
printf "  Repo:  %s\n" "$REPO_ROOT"
printf "  Dest:  %s\n" "$DEST"
printf "  Teams: %s\n" "${#SELECTED[@]}"
$USE_LINK && printf "  Mode:  symlink (--link)\n"
printf "\n"

if $DRY_RUN; then
  for division in "${SELECTED[@]}"; do
    n="$(division_files "$division" | grep -c . || true)"
    printf '  %-22s %3s agents -> %s/%s/\n' "$division" "$n" "$DEST" "$division"
  done
  printf "\n"; dim "  Dry run: nothing written."; exit 0
fi

TOTAL_AGENTS=0
CREATED=0
for division in "${SELECTED[@]}"; do
  label="$(division_label "$division")"
  proj="$DEST/$division"
  agents_dir="$proj/.claude/agents"
  count=0

  mkdir -p "$agents_dir"
  while IFS= read -r f; do
    install_file "$f" "$agents_dir/$(basename "$f")"
    incr count
  done < <(division_files "$division")

  if [[ "$count" -eq 0 ]]; then
    warn "$division: no agents found, skipping"
    rm -rf "$proj"
    continue
  fi

  if [[ -f "$proj/CLAUDE.md" ]] && ! $FORCE; then
    warn "$division: CLAUDE.md exists, keeping it (--force overwrites)"
  else
    write_claude_md "$division" "$label" "$proj"
  fi

  incr_ok=$count
  TOTAL_AGENTS=$(( TOTAL_AGENTS + incr_ok ))
  incr CREATED
  ok "$label: $count agents -> $proj"
done

# Top-level index so the destination folder is self-explaining.
{
  printf '# The Agency — Team Projects\n\n'
  printf 'One Claude Code project per Agency team. Open a folder in the Claude Code\n'
  printf 'desktop app (File > Open) or `cd` into it and run `claude` -- the team'"'"'s\n'
  printf 'agents load automatically from its `.claude/agents/`.\n\n'
  # List every team present on disk, not just this run's selection, so a
  # filtered re-run never shrinks the index.
  for division in "${ALL_DIVISIONS[@]}"; do
    [[ -d "$DEST/$division/.claude/agents" ]] || continue
    n="$(find "$DEST/$division/.claude/agents" -name '*.md' 2>/dev/null | grep -c . || true)"
    printf -- '- `%s/` — %s (%s agents)\n' "$division" "$(division_label "$division")" "$n"
  done
  printf '\nGenerated by `scripts/create-team-projects.sh`.\n'
} > "$DEST/README.md"

printf "\n"
ok "Done: $CREATED team projects, $TOTAL_AGENTS agents -> $DEST"
dim "  Open a team folder in Claude Code desktop, or: cd $DEST/<team> && claude"
